apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-dv-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - datavault-doc.ownyourdata.eu
    secretName: letsencrypt-api-dv
  rules:
  - host: datavault-doc.ownyourdata.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: api-dv-service
          servicePort: 80
